config:
  credentials: []
  project_repos:
    github.com/AI4S2S/lilio:
      branch: main
      repo: https://github.com/AI4S2S/lilio
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-mustard-mule.sh
        container: qc.acc_sleepy-ultramarine-indri
  QC.Doc:
    repos:
      github.com/AI4S2S/lilio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-dandelion-antelope.sh
        container: qc.doc_seedy-scarlet-chameleon
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-xanthic-saola.sh
        container: qc.doc_freaky-olive-cattle
      github.com/AI4S2S/lilio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-sepia-grasshopper.sh
        container: qc.doc_boozy-magnolia-lionfish
      github.com/AI4S2S/lilio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-white-chin.sh
        container: qc.doc_blurry-plum-tuatara
  QC.Lic:
    repos:
      github.com/AI4S2S/lilio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-salmon-wasp.sh
        container: qc.lic_thirsty-aquamarine-dugong
  QC.Met:
    repos:
      github.com/AI4S2S/lilio cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-teal-dugong.sh
        container: qc.met_surly-chartreuse-slug
  QC.Sec:
    repos:
      github.com/AI4S2S/lilio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cinnabar-camel.sh
        container: qc.sec_fuzzy-emerald-squirrel
  QC.Sty:
    repos:
      github.com/AI4S2S/lilio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-black-bandicoot.sh
        container: qc.sty_pasty-cinnamon-lion
      github.com/AI4S2S/lilio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-rose-rattlesnake.sh
        container: qc.sty_crabby-orchid-monster
  QC.Ver:
    repos:
      github.com/AI4S2S/lilio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orange-sparrow.sh
        container: qc.ver_squirrely-black-llama
timeout: 5400
