config:
  credentials: []
  project_repos:
    github.com/AI4S2S/lilio:
      branch: flake8
      repo: https://github.com/AI4S2S/lilio
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-burgundy-jellyfish.sh
        container: qc.acc_sleazy-dandelion-dane
  QC.Doc:
    repos:
      github.com/AI4S2S/lilio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-blue-terrier.sh
        container: qc.doc_craggy-celadon-wrasse
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cerise-bandicoot.sh
        container: qc.doc_silly-ruby-lionfish
      github.com/AI4S2S/lilio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-white-capybara.sh
        container: qc.doc_cozy-bistre-foxhound
      github.com/AI4S2S/lilio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-yellow-sloth.sh
        container: qc.doc_flaky-crimson-stoat
  QC.Lic:
    repos:
      github.com/AI4S2S/lilio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-champagne-caracal.sh
        container: qc.lic_clammy-jade-husky
  QC.Met:
    repos:
      github.com/AI4S2S/lilio cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-orange-spitz.sh
        container: qc.met_breezy-firebrick-emu
  QC.Sec:
    repos:
      github.com/AI4S2S/lilio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-gold-snail.sh
        container: qc.sec_pasty-orchid-baboon
  QC.Sty:
    repos:
      github.com/AI4S2S/lilio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-indigo-quoll.sh
        container: qc.sty_squirrely-ruby-heron
      github.com/AI4S2S/lilio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-tan-penguin.sh
        container: qc.sty_gloppy-grey-shrimp
  QC.Ver:
    repos:
      github.com/AI4S2S/lilio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-orange-quoll.sh
        container: qc.ver_hasty-magenta-lemur
timeout: 5400
