config:
  credentials: []
  project_repos:
    github.com/AI4S2S/lilio:
      branch: main
      repo: https://github.com/AI4S2S/lilio
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cornflower-anteater.sh
        container: qc.acc_sunny-cerise-zebu
  QC.Doc:
    repos:
      github.com/AI4S2S/lilio find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ultramarine-eagle.sh
        container: qc.doc_nippy-periwinkle-ferret
      github.com/AI4S2S/lilio git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-black-beaver.sh
        container: qc.doc_sleepy-wisteria-havanese
      github.com/AI4S2S/lilio markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-violet-chihuahua.sh
        container: qc.doc_tasty-peach-yak
      github.com/AI4S2S/lilio restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-saffron-dalmatian.sh
        container: qc.doc_freaky-gold-beaver
  QC.Lic:
    repos:
      github.com/AI4S2S/lilio licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-lilac-macaque.sh
        container: qc.lic_seedy-cobalt-squirt
  QC.Met:
    repos:
      github.com/AI4S2S/lilio cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-denim-antelope.sh
        container: qc.met_woolly-linen-worm
  QC.Sec:
    repos:
      github.com/AI4S2S/lilio bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-puce-budgerigar.sh
        container: qc.sec_grumpy-green-wallaby
  QC.Sty:
    repos:
      github.com/AI4S2S/lilio flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chocolate-dunker.sh
        container: qc.sty_lovely-beige-anteater
      github.com/AI4S2S/lilio jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-vermilion-balinese.sh
        container: qc.sty_stinky-violet-chipmunk
  QC.Ver:
    repos:
      github.com/AI4S2S/lilio get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amber-lizard.sh
        container: qc.ver_lumpy-crimson-burmese
timeout: 5400
